import { describe, it, expect } from 'bun:test';
import { loadGithubActivity } from '../../src/lib/github-activity';

// The snapshot is generated by scripts/sync-github-activity.mjs (daily in CI)
// and committed. These tests guard the committed payload: schema validity via
// the loader (which reuses chartFileSchema) and the presence of the headline
// stats the /about section renders.
describe('github-activity payload (src/data/github-activity.json)', () => {
  it('loads and passes the schema', () => {
    const data = loadGithubActivity();
    expect(data).not.toBeNull();
  });

  it('carries the five automated charts', () => {
    const data = loadGithubActivity();
    const ids = data!.charts.map((c) => c.id);
    expect(ids).toEqual([
      'activity-30d',
      'monthly-contributions',
      'weekly-contributions',
      'contribution-types',
      'top-languages',
    ]);
  });

  it('exposes numeric headline stats', () => {
    const { stats } = loadGithubActivity()!;
    for (const value of Object.values(stats)) {
      expect(typeof value).toBe('number');
      expect(Number.isFinite(value)).toBe(true);
    }
    expect(stats.activeSince).toBeGreaterThanOrEqual(2008);
  });
});
